apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: jokheywf4-nodejs 
  janus-idp.io/tekton: jokheywf4-nodejs
  backstage.io/kubernetes-id: jokheywf4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jokheywf4-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml